spring:
  datasource:
    # url: "jdbc:h2:mem:testdb"   --- in memory
    url: "jdbc:h2:file:/Users/3724872/h2db/demo"   # file storage
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2: 
    console.enabled: true
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  
spring.jpa.defer-datasource-initialization: true
